<?php
// module/Nf/view/nf/nf/delete.phtml:

$title = 'Delete nf';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Etes vous sur de vouloir supprimer ce dossier
    '<?php echo $this->escapeHtml($nf->title); ?>' by
    '<?php echo $this->escapeHtml($nf->artist); ?>'?
</p>
<?php
$url = $this->url('nf', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $nf->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>